---
services:
  synergy:
    image: tellernotfound/synergy-server-docker:latest
    restart: unless-stopped
    container_name: synergy-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      PLAYERS: 16  # Optional but recommended
      SERVER_PASSWORD: "multigordonfreemen"  # Optional but recommended
      COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "synergy-server-docker by Teller"
      SERVER_DESCRIPTION: "synergy-server-docker by Teller"
    volumes:
      - ./synergy:/synergy/
